name: _
publish_to: none

environment:
  sdk: ^3.13.0-0

workspace:
  - examples/hello_world_custom
  - pkg/wasm_tools/example/greeting

  - pkg/wasm_components
  - pkg/wasm_tools

dev_dependencies:
  lints: ^6.1.0

dependency_overrides:
  package_config: ^3.0.0
