import 'dart:typed_data';

import 'package:wasm_builder/wasm_builder.dart' as w;
// ignore: implementation_imports
import 'package:wasm_builder/src/builder/util.dart';

/// Patches a WebAssembly module generated by `dart2wasm` to reduce host
/// imports.
final class ModuleTransformer {
  final w.Module module;

  late final Map<String, w.Export> _exports = {
    for (final export in module.exports.exported) export.name: export,
  };

  ModuleTransformer(this.module);

  factory ModuleTransformer.fromBytes(Uint8List moduleBytes) {
    return ModuleTransformer(w.Module.deserialize(w.Deserializer(moduleBytes)));
  }

  Uint8List serialize() {
    final serializer = w.Serializer();
    module.serialize(serializer);
    return serializer.data;
  }

  void transform() {
    _patchImports();
    _removeExports();
  }

  void _patchImports() {
    final Map<w.ImportedFunction, w.DefinedFunction> patchFunctions = {};

    for (final import in module.imports.all) {
      if (import is w.ImportedFunction && import.module == 'dart') {
        if (_exports[import.name] case final export?) {
          if (export case w.FunctionExport(
            function: final w.DefinedFunction fn,
          )) {
            patchFunctions[import] = fn;
            continue;
          }
        }

        if (import.name == 'print') continue; // TODO
      }

      throw 'TODO: Unknown import $import';
    }

    for (final removedImport in patchFunctions.keys) {
      module.imports.functions.remove(removedImport);
      module.imports.all.remove(removedImport);
    }

    print('Patching ${patchFunctions.length} functions');
    var patchedReferences = 0;
    for (final function in module.functions.defined) {
      for (final instr in function.body.instructions) {
        if (instr is w.Call) {
          final replacement = patchFunctions[instr.function];
          if (replacement != null) {
            instr.function = replacement;
            patchedReferences++;
          }
        }
        if (instr is w.RefFunc) {
          final replacement = patchFunctions[instr.function];
          if (replacement != null) {
            instr.function = replacement;
            patchedReferences++;
          }
        }
      }
    }

    print('Patched $patchedReferences references');
    finalizeImportsAndDefinitions(
      module.functions.imported,
      module.functions.defined,
    );
  }

  void _removeExports() {
    for (final export in _exports.values) {
      if (export.name != r'$invokeMain') {
        module.exports.exported.remove(export);
      }
    }
  }
}
