import 'dart:typed_data';

import '../third_party/wasm_builder/wasm_builder.dart' as w;
import '../third_party/wasm_builder/src/builder/util.dart';
import 'program_abi.dart';
import 'compiler.dart';

/// Patches a WebAssembly module generated by `dart2wasm` to reduce host
/// imports.
final class ModuleTransformer {
  final w.Module module;

  late final Map<String, w.Export> _exports = {
    for (final export in module.exports.exported) export.name: export,
  };

  ModuleTransformer(this.module);

  factory ModuleTransformer.fromBytes(Uint8List moduleBytes) {
    return ModuleTransformer(w.Module.deserialize(w.Deserializer(moduleBytes)));
  }

  Uint8List serialize() {
    final serializer = w.Serializer();
    module.serialize(serializer);
    return serializer.data;
  }

  void transform(DartProgramAbi abi) {
    _patchImports(abi);
    _removeExports(abi.functionExports.keys.toSet());
    _addExportedStartFunction();
  }

  void _patchImports(DartProgramAbi abi) {
    final Map<w.ImportedFunction, w.DefinedFunction> patchFunctions = {};
    final unusedComponentImports = abi.functionImports.keys.toSet();

    for (final import in module.imports.all) {
      if (import is w.ImportedFunction && import.module == 'dart') {
        if (_exports[import.name] case final export?) {
          if (export case w.FunctionExport(
            function: final w.DefinedFunction fn,
          )) {
            patchFunctions[import] = fn;
            continue;
          }
        }
      }

      if (import.module == 'libc') continue;
      if (import.module == 'component') {
        if (!unusedComponentImports.remove(import.name)) {
          throw CompilerFailure(
            'Import runtime.${import.name} is not registered in ABI.',
          );
        }

        continue;
      }

      throw 'TODO: Unknown import ${import.module}:${import.name}';
    }

    for (final removedImport in patchFunctions.keys) {
      module.imports.functions.remove(removedImport);
      module.imports.all.remove(removedImport);
    }

    print('Patching ${patchFunctions.length} functions');
    var patchedReferences = 0;
    for (final function in module.functions.defined) {
      for (final instr in function.body.instructions) {
        if (instr is w.Call) {
          final replacement = patchFunctions[instr.function];
          if (replacement != null) {
            instr.function = replacement;
            patchedReferences++;
          }
        }
        if (instr is w.RefFunc) {
          final replacement = patchFunctions[instr.function];
          if (replacement != null) {
            instr.function = replacement;
            patchedReferences++;
          }
        }
      }
    }

    print('Patched $patchedReferences references');
    finalizeImportsAndDefinitions(
      module.functions.imported,
      module.functions.defined,
    );
  }

  void _removeExports(Set<String> expectedExports) {
    for (final export in _exports.values) {
      if (!expectedExports.remove(export.name)) {
        module.exports.exported.remove(export);
      }
    }

    if (expectedExports.isNotEmpty) {
      throw ArgumentError('Expected compiled app to export $expectedExports');
    }
  }

  void _addExportedStartFunction() {
    final mainFunction =
        (_exports[r'$invokeMain'] as w.FunctionExport).function;
    final argsArrayType =
        (mainFunction.type.inputs[0] as w.RefType).containedDefType
            as w.ArrayType;

    final emptyFunctionType = module.types.defined
        .whereType<w.FunctionType>()
        .firstWhere((e) => e.inputs.isEmpty && e.outputs.isEmpty);

    final startFunction = w.DefinedFunction(
      module,
      w.Instructions(
        [],
        {},
        [
          w.I32Const(0),
          w.ArrayNewDefault(argsArrayType),
          w.Call(mainFunction),
          w.End(),
        ],
        null,
        [],
        [],
      ),
      w.FinalizableIndex(),
      emptyFunctionType,
      '_start',
    );
    startFunction.finalizableIndex.value =
        module.functions.defined.last.index + 1;
    module.functions.defined.add(startFunction);
    module.exports.exported.add(w.FunctionExport('_start', startFunction));
  }
}
