import 'dart:typed_data';

import '../third_party/wasm_builder/wasm_builder.dart' as w;
import '../third_party/wasm_builder/src/builder/util.dart';

/// Patches a WebAssembly module generated by `dart2wasm` to reduce host
/// imports.
final class ModuleTransformer {
  final w.Module module;

  late final Map<String, w.Export> _exports = {
    for (final export in module.exports.exported) export.name: export,
  };

  ModuleTransformer(this.module);

  factory ModuleTransformer.fromBytes(Uint8List moduleBytes) {
    return ModuleTransformer(w.Module.deserialize(w.Deserializer(moduleBytes)));
  }

  Uint8List serialize() {
    final serializer = w.Serializer();
    module.serialize(serializer);
    return serializer.data;
  }

  void transform() {
    _patchImports();
    _removeExports();
    _invokeMainInStartFunction();
  }

  void _patchImports() {
    final Map<w.ImportedFunction, w.DefinedFunction> patchFunctions = {};

    for (final import in module.imports.all) {
      if (import is w.ImportedFunction && import.module == 'dart') {
        if (_exports[import.name] case final export?) {
          if (export case w.FunctionExport(
            function: final w.DefinedFunction fn,
          )) {
            patchFunctions[import] = fn;
            continue;
          }
        }
      }

      if (import.module == 'libc') continue;
      throw 'TODO: Unknown import ${import.module}:${import.name}';
    }

    for (final removedImport in patchFunctions.keys) {
      module.imports.functions.remove(removedImport);
      module.imports.all.remove(removedImport);
    }

    print('Patching ${patchFunctions.length} functions');
    var patchedReferences = 0;
    for (final function in module.functions.defined) {
      for (final instr in function.body.instructions) {
        if (instr is w.Call) {
          final replacement = patchFunctions[instr.function];
          if (replacement != null) {
            instr.function = replacement;
            patchedReferences++;
          }
        }
        if (instr is w.RefFunc) {
          final replacement = patchFunctions[instr.function];
          if (replacement != null) {
            instr.function = replacement;
            patchedReferences++;
          }
        }
      }
    }

    print('Patched $patchedReferences references');
    finalizeImportsAndDefinitions(
      module.functions.imported,
      module.functions.defined,
    );
  }

  void _removeExports() {
    for (final export in _exports.values) {
      module.exports.exported.remove(export);
    }
  }

  void _invokeMainInStartFunction() {
    // Patch the generated
    final mainFunction =
        (_exports[r'$invokeMain'] as w.FunctionExport).function;
    final argsArrayType =
        (mainFunction.type.inputs[0] as w.RefType).containedDefType
            as w.ArrayType;

    List<w.Instruction> instructions;
    if (module.start case final existing?) {
      instructions = (existing as w.DefinedFunction).body.instructions;
    } else {
      instructions = [w.End()];

      final startFunction = w.DefinedFunction(
        module,
        w.Instructions([], {}, instructions, {}, [], []),
        w.FinalizableIndex(),
        w.FunctionType([], []),
      );
      //module.start = startFunction;
    }

    final start = module.start! as w.DefinedFunction;
    final code = start.body.instructions;
    // Insert call to main before End instruction.
    code.insertAll(code.length - 1, [
      w.I32Const(0),
      w.ArrayNewDefault(argsArrayType),
      w.Call(mainFunction),
    ]);
  }
}
