name: wasi_http_service
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  hooks: ^2.0.2
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  wasm_components:
  wasm_tools:
  wasi:
