package root:component;

world root {
  import wasi:cli/stdout@0.3.0;
  export wasi:cli/run@0.3.0;
}

package wasi:cli@0.3.0 {
  interface stdout {
    use types.{error-code};

    write-via-stream: func(data: stream<u8>) -> future<result<_, error-code>>;
  }

  interface types {
    enum error-code {
      /// Input/output error
      io,
      /// Invalid or incomplete multibyte or wide character
      illegal-byte-sequence,
      /// Broken pipe
      pipe,
    }
  }

  interface run {
    run: async func() -> result;
  }
}
