import 'dart:typed_data';

import 'package:logging/logging.dart';

import '../third_party/wasm_builder/wasm_builder.dart' as w;
import '../third_party/wasm_builder/src/builder/util.dart';
import 'components/linker.dart';
import 'components/type.dart';
import 'dart_linker.dart';
import 'program_abi.dart';
import 'compiler.dart';

/// Patches a WebAssembly module generated by `dart2wasm` to reduce host
/// imports.
final class ModuleTransformer {
  final w.Module module;
  final Logger logger;
  final Map<w.ImportedFunction, w.BaseFunction> _patchFunctions = {};

  late final Map<String, w.Export> _exports = {
    for (final export in module.exports.exported) export.name: export,
  };

  ModuleTransformer(this.module, this.logger);

  factory ModuleTransformer.fromBytes(Uint8List moduleBytes, Logger logger) {
    return ModuleTransformer(
      w.Module.deserialize(w.Deserializer(moduleBytes)),
      logger,
    );
  }

  Uint8List serialize() {
    final serializer = w.Serializer();
    module.serialize(serializer);
    return serializer.data;
  }

  void transform(DartProgramAbi abi) {
    _patchImports(abi);
    final expectedExports = abi.expectedExportedFunctions.toSet();
    if (abi.hasAsyncExport) {
      expectedExports.add('callback');
    }
    _removeExports(expectedExports);
    _runMainOnInstantiation();
  }

  void _patchImports(DartProgramAbi abi) {
    const replacers = {
      'randomInt': _RandomImports(),
      'randomIntSecure': _RandomImports(),
      'wasi_now': _ClockImports(),
      'wasi_iana_id': _ClockImports(),
      'wasi_monotonic_now': _ClockImports(),
      'wasi_monotonic_getResolution': _ClockImports(),
      'wasi_monotonic_waitFor': _ClockImports(),
    };

    final unusedComponentImports = abi.functionImports.keys.toSet();

    for (final import in module.imports.all.toList()) {
      if (import is w.ImportedFunction && import.module == 'dart') {
        if (replacers[import.name] case final replacer?) {
          replacer.addTo(abi, this, import);
          continue;
        } else if (_exports[import.name] case final export?) {
          if (export case w.FunctionExport(
            function: final w.DefinedFunction fn,
          )) {
            if (fn.type != import.type) {
              throw StateError(
                'Could not link ${import.name} due to different types.',
              );
            }

            _patchFunctions[import] = fn;
            continue;
          }
        } else if (_rewriteToRuntimeImports.contains(import.name)) {
          import.module = _runtimeImportName;
          import.name = 'dart_${import.name}';
          continue;
        }
      }

      if (import.module == _runtimeImportName) continue;
      if (import.module == 'component') {
        // These canon. imports are only used in pkg:wasm_components. Other
        // packages encode them in their ABI contributed by build hooks.
        if (import.name.startsWith('canon.')) {
          CanonPrimitive Function(DartLinker) primitive;

          switch (import.name) {
            case 'canon.context.get_i32_0':
              primitive = (linker) => linker.builder.linker.canonContextGet(0);
            case 'canon.context.set_i32_0':
              primitive = (linker) => linker.builder.linker.canonContextSet(0);
            case 'canon.waitable-set.new':
              primitive = (linker) =>
                  linker.builder.linker.addCanonPrimitive(WaitableSetNew.new);
            case 'canon.waitable-set.drop':
              primitive = (linker) =>
                  linker.builder.linker.addCanonPrimitive(WaitableSetDrop.new);
            case 'canon.waitable.join':
              primitive = (linker) =>
                  linker.builder.linker.addCanonPrimitive(WaitableJoin.new);
            case 'canon.future<void>.new':
              primitive = (linker) => linker.builder.linker.addCanonPrimitive(
                (f) => FutureNew(
                  f,
                  linker.builder.types.addValueType(FutureType()),
                ),
              );
            case 'canon.future<void>.read':
              primitive = (linker) =>
                  linker.builder.linker.addCanonPrimitive((f) {
                    final read = FutureRead(
                      f,
                      linker.builder.types.addValueType(FutureType()),
                    );
                    read.async = true;
                    return read;
                  });
            case 'canon.future<void>.write':
              primitive = (linker) =>
                  linker.builder.linker.addCanonPrimitive((f) {
                    final read = FutureWrite(
                      f,
                      linker.builder.types.addValueType(FutureType()),
                    );
                    read.async = true;
                    return read;
                  });
            case 'canon.future<void>.drop-read':
              primitive = (linker) => linker.builder.linker.addCanonPrimitive(
                (f) => FutureDropReadable(
                  f,
                  linker.builder.types.addValueType(FutureType()),
                ),
              );
            case 'canon.future<void>.drop-write':
              primitive = (linker) => linker.builder.linker.addCanonPrimitive(
                (f) => FutureDropWritable(
                  f,
                  linker.builder.types.addValueType(FutureType()),
                ),
              );
            case 'canon.subtask.drop':
              primitive = (linker) =>
                  linker.builder.linker.addCanonPrimitive(CanonSubtaskDrop.new);
            default:
              throw UnsupportedError('Unsupported canon ${import.name}');
          }

          abi.functionImports[import.name] = ImportedCanonPrimitive(
            import.name,
            primitive,
          );
          continue;
        }

        if (!unusedComponentImports.remove(import.name)) {
          throw CompilerFailure(
            'Import component.${import.name} is not registered in ABI.',
          );
        }

        continue;
      }

      throw 'TODO: Unknown import ${import.module}:${import.name}';
    }

    for (final removedImport in _patchFunctions.keys) {
      module.imports.functions.remove(removedImport);
      module.imports.all.remove(removedImport);
    }

    logger.fine('Patching ${_patchFunctions.length} functions');
    var patchedReferences = 0;
    for (final function in module.functions.defined) {
      for (final instr in function.body.instructions) {
        if (instr is w.Call) {
          final replacement = _patchFunctions[instr.function];
          if (replacement != null) {
            instr.function = replacement;
            patchedReferences++;
          }
        }
        if (instr is w.RefFunc) {
          final replacement = _patchFunctions[instr.function];
          if (replacement != null) {
            instr.function = replacement;
            patchedReferences++;
          }
        }
      }
    }

    logger.fine('Patched $patchedReferences references');
    finalizeImportsAndDefinitions(
      module.functions.imported,
      module.functions.defined,
    );
  }

  void _removeExports(Set<String> expectedExports) {
    for (final export in _exports.values) {
      if (!expectedExports.remove(export.name)) {
        module.exports.exported.remove(export);
      }
    }

    if (expectedExports.isNotEmpty) {
      throw ArgumentError('Expected compiled app to export $expectedExports');
    }
  }

  void _runMainOnInstantiation() {
    final mainFunction =
        (_exports[r'$invokeMain'] as w.FunctionExport).function;
    final argsArrayType =
        (mainFunction.type.inputs[0] as w.RefType).containedDefType
            as w.ArrayType;

    final existingStart = module.start;
    final instructionsToInvokeMain = [
      w.I32Const(0),
      w.ArrayNewDefault(argsArrayType),
      w.Call(mainFunction),
    ];

    if (existingStart != null) {
      final body = (existingStart as w.DefinedFunction).body.instructions;
      assert(body.last is w.End);
      body.insertAll(body.length - 1, instructionsToInvokeMain);
    } else {
      final emptyFunctionType = module.types.defined
          .whereType<w.FunctionType>()
          .firstWhere((e) => e.inputs.isEmpty && e.outputs.isEmpty);

      final startFunction = w.DefinedFunction(
        module,
        w.Instructions(
          [],
          {},
          [...instructionsToInvokeMain, w.End()],
          null,
          [],
          [],
        ),
        w.FinalizableIndex(),
        emptyFunctionType,
        '_start',
      );
      startFunction.finalizableIndex.value =
          module.functions.defined.last.index + 1;
      module.functions.defined.add(startFunction);
      module.start = startFunction;
    }
  }
}

const _runtimeImportName = 'libc';

const _rewriteToRuntimeImports = {
  'mathPow',
  'mathAtan2',
  'mathSin',
  'mathCos',
  'mathTan',
  'mathAcos',
  'mathAsin',
  'mathAtan',
  'mathExp',
  'mathLog',
};

abstract base class _ComponentImport {
  const _ComponentImport();

  void addTo(
    DartProgramAbi abi,
    ModuleTransformer transformer,
    w.ImportedFunction function,
  );
}

final class _RandomImports extends _ComponentImport {
  const _RandomImports();

  @override
  void addTo(
    DartProgramAbi abi,
    ModuleTransformer transformer,
    w.ImportedFunction function,
  ) {
    final isSecure = function.name == 'randomIntSecure';
    final interface = isSecure
        ? _lookupSecureRandom(abi)
        : _lookupInsecureRandom(abi);
    final methodName = isSecure ? 'get-random-u64' : 'get-insecure-random-u64';

    final coreImportName = 'implicitImport_${function.name}';
    final import = w.ImportedFunction(
      transformer.module,
      'component',
      coreImportName,
      w.FinalizableIndex(),
      function.type,
    );
    transformer.module.imports
      ..all.add(import)
      ..functions.add(import);

    final componentImport = ImportedInstanceFunction(
      methodName,
      coreImportName,
      FunctionOptions(usesMemory: false, usesStrings: false),
    );
    abi.functionImports[coreImportName] = componentImport;
    interface.importedFunctions.add(componentImport);

    transformer._patchFunctions[function] = import;
  }

  ResolvedInterface _lookupInsecureRandom(DartProgramAbi abi) {
    const fullName = 'wasi:random/insecure@0.3.0';

    return abi.lookupOrAddInterface(fullName, () {
      final builder = InstanceTypeBuilder()
        ..exportFunction('get-insecure-random-bytes', _generateBytes())
        ..exportFunction('get-insecure-random-u64', _generateU64());

      return ResolvedInterface(fullName, builder.build());
    });
  }

  ResolvedInterface _lookupSecureRandom(DartProgramAbi abi) {
    const fullName = 'wasi:random/random@0.3.0';

    return abi.lookupOrAddInterface(fullName, () {
      final builder = InstanceTypeBuilder()
        ..exportFunction('get-random-bytes', _generateBytes())
        ..exportFunction('get-random-u64', _generateU64());

      return ResolvedInterface(fullName, builder.build());
    });
  }

  FunctionType _generateBytes() {
    return FunctionType(
      async: false,
      parameters: [.new(label: 'max-len', type: PrimitiveType.u64)],
      result: VariableLengthListType(elementType: PrimitiveType.u8),
    );
  }

  FunctionType _generateU64() {
    return FunctionType(
      async: false,
      parameters: [],
      result: PrimitiveType.u64,
    );
  }
}

final class _ClockImports extends _ComponentImport {
  const _ClockImports();

  @override
  void addTo(
    DartProgramAbi abi,
    ModuleTransformer transformer,
    w.ImportedFunction function,
  ) {
    switch (function.name) {
      case 'wasi_now':
        if (!_functionUsed(transformer, 'currentTime')) {
          _stubPtr(transformer, function);
          break;
        }

        final systemClock = _lookupSystemClock(abi);
        function.module = 'component';
        function.name = 'implicitImport_systemClockNow';
        final componentImport = ImportedInstanceFunction(
          'now',
          function.name,
          FunctionOptions(usesMemory: true, usesStrings: false),
        );
        abi.functionImports[function.name] = componentImport;
        systemClock.importedFunctions.add(componentImport);
      case 'wasi_iana_id':
        if (!_functionUsed(transformer, 'timeZoneNameForClampedSeconds')) {
          _stubPtr(transformer, function);
          break;
        }

        final timezone = _lookupTimezone(abi);
        function.module = 'component';
        function.name = 'implicitImport_timezoneIanaId';
        final componentImport = ImportedInstanceFunction(
          'iana-id',
          function.name,
          FunctionOptions(
            usesMemory: true,
            usesStrings: true,
            needsRealloc: true,
          ),
        );
        abi.functionImports[function.name] = componentImport;
        timezone.importedFunctions.add(componentImport);
      case 'wasi_monotonic_now':
        if (!_functionUsed(transformer, 'monotonicClockTicks')) {
          _stubReturningI64(transformer, function);
          break;
        }
        final clock = _lookupMonotonicClock(abi);
        function.module = 'component';
        function.name = 'implicitImport_monotonicTicks';
        final componentImport = ImportedInstanceFunction(
          'now',
          function.name,
          FunctionOptions(usesMemory: false, usesStrings: false),
        );
        abi.functionImports[function.name] = componentImport;
        clock.importedFunctions.add(componentImport);
      case 'wasi_monotonic_getResolution':
        if (!_functionUsed(transformer, 'monotonicClockFrequency') &&
            !_functionUsed(transformer, 'monotonicClockTicks')) {
          _stubReturningI64(transformer, function);
          break;
        }
        final clock = _lookupMonotonicClock(abi);
        function.module = 'component';
        function.name = 'implicitImport_monotonicDuration';
        final componentImport = ImportedInstanceFunction(
          'get-resolution',
          function.name,
          FunctionOptions(usesMemory: false, usesStrings: false),
        );
        abi.functionImports[function.name] = componentImport;
        clock.importedFunctions.add(componentImport);
      case 'wasi_monotonic_waitFor':
        final clock = _lookupMonotonicClock(abi);
        function.module = 'component';
        function.name = 'implicitImport_monotonicWaitFor';
        final componentImport = ImportedInstanceFunction(
          'wait-for',
          function.name,
          FunctionOptions(usesMemory: false, usesStrings: false, async: true),
        );
        abi.functionImports[function.name] = componentImport;
        clock.importedFunctions.add(componentImport);
    }
  }

  bool _functionUsed(ModuleTransformer transformer, String name) {
    return transformer.module.imports.functions.any(
      (e) => e.module == 'dart' && e.name == name,
    );
  }

  /// Replaces the `wasiNowPtr()` import with a stub to avoid dependencies.
  void _stubPtr(
    ModuleTransformer transformer,
    w.ImportedFunction importedFunction,
  ) {
    final stubFunction = w.DefinedFunction(
      transformer.module,
      w.Instructions([], {}, [w.End()], null, [], []),
      w.FinalizableIndex(),
      importedFunction.type,
    );
    transformer.module.functions.defined.add(stubFunction);
    transformer._patchFunctions[importedFunction] = stubFunction;
  }

  // Replaces `wasiMonotonicNow()` and `wasiMonotonicGetResolution` with a stub.
  void _stubReturningI64(
    ModuleTransformer transformer,
    w.ImportedFunction importedFunction,
  ) {
    final stubFunction = w.DefinedFunction(
      transformer.module,
      w.Instructions([], {}, [w.I64Const(0), w.End()], null, [], []),
      w.FinalizableIndex(),
      importedFunction.type,
    );
    transformer.module.functions.defined.add(stubFunction);
    transformer._patchFunctions[importedFunction] = stubFunction;
  }

  ResolvedInterface _lookupSystemClock(DartProgramAbi abi) {
    const fullName = 'wasi:clocks/system-clock@0.3.0';

    return abi.lookupOrAddInterface(fullName, () {
      final instance = InstanceTypeBuilder();
      final instant = instance.exportType(
        'instant',
        RecordType([
          .new(label: 'seconds', type: PrimitiveType.s64),
          .new(label: 'nanoseconds', type: PrimitiveType.u32),
        ]),
      );
      instance.exportFunction(
        'now',
        FunctionType(async: false, parameters: [], result: instant),
      );
      instance.exportFunction(
        'get-resolution',
        FunctionType(async: false, parameters: [], result: PrimitiveType.u64),
      );

      return ResolvedInterface(fullName, instance.build());
    });
  }

  ResolvedInterface _lookupTimezone(DartProgramAbi abi) {
    const fullName = 'wasi:clocks/timezone@0.3.0';

    return abi.lookupOrAddInterface(fullName, () {
      final instance = InstanceTypeBuilder();

      instance.exportFunction(
        'iana-id',
        FunctionType(
          async: false,
          parameters: [],
          result: OptionType(StringType()),
        ),
      );

      return ResolvedInterface(fullName, instance.build());
    });
  }

  ResolvedInterface _lookupMonotonicClock(DartProgramAbi abi) {
    const fullName = 'wasi:clocks/monotonic-clock@0.3.0';

    return abi.lookupOrAddInterface(fullName, () {
      final instance = InstanceTypeBuilder();

      instance.exportFunction(
        'now',
        FunctionType(async: false, parameters: [], result: PrimitiveType.u64),
      );
      instance.exportFunction(
        'get-resolution',
        FunctionType(async: false, parameters: [], result: PrimitiveType.u64),
      );
      instance.exportFunction(
        'wait-for',
        FunctionType(
          async: true,
          parameters: [.new(label: 'how-long', type: PrimitiveType.u64)],
          result: null,
        ),
      );

      return ResolvedInterface(fullName, instance.build());
    });
  }
}
