import 'dart:io';

void main() {
  final buffer = StringBuffer('''
// dart format off
// Generated by tool/generate_constants.dart

// ignore: import_internal_library
import 'dart:_wasm';

import 'string.dart';

''');

  void defineCharCodes(String constantName, String contents, {bool i8 = true}) {
    final elementType = i8 ? 'WasmI8' : 'WasmI16';
    buffer.writeln('/// Char codes of `$contents`');
    buffer.writeln(
      'const WasmArray<$elementType> $constantName = WasmArray.literal(['
      '${contents.codeUnits.join(', ')}'
      ']);',
    );
  }

  void defineString(
    String constantName,
    String contents, {
    bool latin1 = true,
  }) {
    final typeName = latin1 ? 'Latin1String' : 'Utf16String';

    buffer.writeln('/// The string `$contents`');
    buffer.writeln(
      'const $typeName $constantName = $typeName.unsafeWrap(WasmArray.literal(['
      '${contents.codeUnits.join(', ')}'
      ']));',
    );
  }

  defineString(
    'stackTracesAreUnavailableMessage',
    'Stack traces are unavailable in WASM component builds',
  );
  defineString(r'$0', '0');
  defineCharCodes('digits', '0123456789abcdefghijklmnopqrstuvwxyz');

  File('lib/src/embedder/constants.dart').writeAsStringSync(buffer.toString());
}
