name: greeting
description: A sample command-line application.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0-0

dependencies:
  hooks: ^2.0.2
  wasm_components:
  wasm_tools:
