name: wasm_components
description: Runtime definitions to help run Dart apps as WebAssembly components.
resolution: workspace
version: 0.1.0-preview.0
repository: https://github.com/simolus3/wasm.dart/
environment:
  sdk: ^3.13.0-0

dependencies:
  collection: ^1.19.1
  meta: ^1.18.3

dev_dependencies:
  test: ^1.31.1
