name: wasm_components
description: Create and consume WebAssembly components with Dart.
resolution: workspace
environment:
  sdk: ^3.12.0

dependencies:
  collection: ^1.19.1
  logging: ^1.3.0
  path: ^1.9.1
