name: Download and compile SQLite

on:
  workflow_call:
    outputs:
      asset_id:
        description: "ID of the artifact containing runtime_helpers.wasm"
        value: ${{ jobs.merge_results.outputs.libs }}

permissions:
  contents: read

jobs:
  build_runtime_helpers_wasm:
    name: Build runtime_helpers.wasm
    runs-on: ubuntu-latest
    outputs:
      wasm: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/cache@v5
        id: cache_build
        with:
          path: pkg/wasm_tools/assets/runtime_helpers.wasm
          key: runtime-helpers-${{ hashFiles('Cargo.lock', 'pkg/runtime_helpers/**') }}
      - name: Install rust
        if: steps.cache_build.outputs.cache-hit != 'true'
        run: rustup toolchain install nightly --component rust-src

      - name: Compile runtime
        if: steps.cache_build.outputs.cache-hit != 'true'
        working-directory: pkg/wasm_tools
        run: ./tool/build_runtime_helpers.sh

      - name: Upload binaries
        uses: actions/upload-artifact@v7
        id: upload
        with:
          name: runtime-helpers
          path: pkg/wasm_tools/assets/runtime_helpers.wasm
          if-no-files-found: error
          retention-days: 1

  build_witgen_linux:
    name: Build wit_bindgen_dart for Linux
    runs-on: ubuntu-latest
    outputs:
      built: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/cache@v5
        id: cache_build
        with:
          path: pkg/wasm_tools/lib/src/wit_gen/precompiled
          key: bindgen-linux-${{ hashFiles('Cargo.lock', 'pkg/wit_bindgen_dart/**') }}
      - name: Install rust
        if: steps.cache_build.outputs.cache-hit != 'true'
        run: |
          rustup toolchain install
          rustup target add x86_64-unknown-linux-gnu
          rustup target add aarch64-unknown-linux-gnu
          rustup target add riscv64gc-unknown-linux-gnu
          rustup target add armv7-unknown-linux-gnueabihf
      - name: Install cross-compiling GCC
        if: steps.cache_build.outputs.cache-hit != 'true'
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu gcc-riscv64-linux-gnu gcc-arm-linux-gnueabihf
      - name: Build for Linux
        if: steps.cache_build.outputs.cache-hit != 'true'
        run: |
          cargo build --release -p wit_bindgen_dart --target x86_64-unknown-linux-gnu
          cargo build --release -p wit_bindgen_dart --target aarch64-unknown-linux-gnu
          cargo build --release -p wit_bindgen_dart --target armv7-unknown-linux-gnueabihf
          cargo build --release -p wit_bindgen_dart --target riscv64gc-unknown-linux-gnu
      - name: Copy libraries
        if: steps.cache_build.outputs.cache-hit != 'true'
        working-directory: pkg/wasm_tools
        run: |
          mkdir lib/src/wit_gen/precompiled
          cp ../../target/x86_64-unknown-linux-gnu/release/libwit_bindgen_dart.so lib/src/wit_gen/precompiled/libwit_bindgen_dart.linux_x64.so
          cp ../../target/aarch64-unknown-linux-gnu/release/libwit_bindgen_dart.so lib/src/wit_gen/precompiled/libwit_bindgen_dart.linux_aarch64.so
          cp ../../target/armv7-unknown-linux-gnueabihf/release/libwit_bindgen_dart.so lib/src/wit_gen/precompiled/libwit_bindgen_dart.linux_arm7.so
          cp ../../target/riscv64gc-unknown-linux-gnu/release/libwit_bindgen_dart.so lib/src/wit_gen/precompiled/libwit_bindgen_dart.linux_riscv.so
      - uses: actions/upload-artifact@v7
        with:
          name: witgen-linux
          retention-days: 1
          path: pkg/wasm_tools/lib/src/wit_gen/precompiled/

  build_witgen_macos:
    name: Build wit_bindgen_dart for macOS
    runs-on: macos-latest
    outputs:
      built: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/cache@v5
        id: cache_build
        with:
          path: pkg/wasm_tools/lib/src/wit_gen/precompiled
          key: bindgen-macos-${{ hashFiles('Cargo.lock', 'pkg/wit_bindgen_dart/**') }}
      - name: Install rust
        if: steps.cache_build.outputs.cache-hit != 'true'
        run: |
          rustup toolchain install
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin
      - name: Build for macOS
        if: steps.cache_build.outputs.cache-hit != 'true'
        run: |
          cargo build --release -p wit_bindgen_dart --target x86_64-apple-darwin
          cargo build --release -p wit_bindgen_dart --target aarch64-apple-darwin
      - name: Copy libraries
        if: steps.cache_build.outputs.cache-hit != 'true'
        working-directory: pkg/wasm_tools
        run: |
          mkdir lib/src/wit_gen/precompiled
          cp ../../target/x86_64-apple-darwin/release/libwit_bindgen_dart.dylib lib/src/wit_gen/precompiled/libwit_bindgen_dart.macos_x64.so
          cp ../../target/aarch64-apple-darwin/release/libwit_bindgen_dart.dylib lib/src/wit_gen/precompiled/libwit_bindgen_dart.macos_aarch64.so
      - uses: actions/upload-artifact@v7
        with:
          name: witgen-macos
          retention-days: 1
          path: pkg/wasm_tools/lib/src/wit_gen/precompiled/

  build_witgen_windows:
    name: Build wit_bindgen_dart for Windows
    runs-on: windows-latest
    outputs:
      built: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/cache@v5
        id: cache_build
        with:
          path: pkg/wasm_tools/lib/src/wit_gen/precompiled
          key: bindgen-windows-${{ hashFiles('Cargo.lock', 'pkg/wit_bindgen_dart/**') }}
      - name: Install rust
        if: steps.cache_build.outputs.cache-hit != 'true'
        run: |
          rustup toolchain install
          rustup target add x86_64-pc-windows-msvc
          rustup target add aarch64-pc-windows-msvc
      - name: Build for Windows
        if: steps.cache_build.outputs.cache-hit != 'true'
        run: |
          cargo build --release -p wit_bindgen_dart --target x86_64-pc-windows-msvc
          cargo build --release -p wit_bindgen_dart --target aarch64-pc-windows-msvc
      - name: Copy libraries
        if: steps.cache_build.outputs.cache-hit != 'true'
        working-directory: pkg/wasm_tools
        run: |
          mkdir lib/src/wit_gen/precompiled
          cp ../../target/x86_64-pc-windows-msvc/release/wit_bindgen_dart.dll lib/src/wit_gen/precompiled/libwit_bindgen_dart.win_x64.dll
          cp ../../target/aarch64-pc-windows-msvc/release/wit_bindgen_dart.dll lib/src/wit_gen/precompiled/libwit_bindgen_dart.win_aarch64.dll
      - uses: actions/upload-artifact@v7
        with:
          name: witgen-windows
          retention-days: 1
          path: pkg/wasm_tools/lib/src/wit_gen/precompiled/

  merge_results:
    name: Merge results into single asset
    needs:
      - build_runtime_helpers_wasm
      - build_witgen_linux
      - build_witgen_macos
      - build_witgen_windows
    runs-on: ubuntu-slim
    outputs:
      libs: ${{ steps.upload_libs.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: actions/download-artifact@v8
        with:
          path: pkg/wasm_tools/assets/
          pattern: runtime-helpers

      - uses: actions/download-artifact@v8
        with:
          path: pkg/wasm_tools/lib/src/wit_gen/precompiled/
          merge-multiple: true
          pattern: witgen-*

      - name: Upload runtime and CLI helper libraries
        uses: actions/upload-artifact@v7
        id: upload_libs
        with:
          name: helper-libs
          path: |
            pkg/wasm_tools/assets/runtime_helpers.wasm
            pkg/wasm_tools/lib/src/wit_gen/precompiled/
          if-no-files-found: error
          retention-days: 1
